# Generated by Django 4.2.23 on 2025-08-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0002_rename_unit_ingredient_measurement_unit"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("name", "measurement_unit"), name="unique_ingredient"
            ),
        ),
    ]
