# Generated by Django 4.2.23 on 2025-08-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0003_ingredient_unique_ingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="Название"
            ),
        ),
    ]
