# Generated by Django 4.2.23 on 2025-08-10 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredient_name'),
        ('recipes', '0002_shoppingcart_favourite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_list', to='ingredients.ingredient', verbose_name='Ингредиент'),
        ),
    ]
